### ISSUE TITLE
Can u make hack for increase stat asura

### ISSUE THREAD

**Issue by AlanNois** [kruvcraft21/OTLScript#1]
Can u make hack for increase stat asura, it take too much time to do it with gem

**Comment by kruvcraft21** [comment]
i think i could do it

**Comment by kruvcraft21** [comment]
@AlanNois. asura points, as well as the stones you spend to get them, are encrypted by the game. Hacking is not a problem, but there is an option that you can get your account blocked

![Asura power](https://user-images.githubusercontent.com/33977897/211628298-273b3081-33b3-4b4a-9b56-354f143267b9.png)
