### ISSUE TITLE
Mirage Pass

### ISSUE THREAD

**Issue by NODEJSandPYTHONismylove** [kruvcraft21/OTLScript#2]
Can we hack exp of mirage pass

**Comment by kruvcraft21** [comment]
It's over possible, I guess, but I don't want to do it, as it can kill the desire to play the game.

**Comment by kruvcraft21** [comment]
It's over possible, I guess, but I don't want to do it, as it can kill the desire to play the game.

**Comment by NODEJSandPYTHONismylove** [comment]
Yeah i know, but can u just only show me how to hack it?

**Comment by kruvcraft21** [comment]
I didn't say I knew, I wrote that it might be possible.
