### ISSUE TITLE
Break item from store not work

### ISSUE THREAD

**Issue by WuzenLiz** [kruvcraft21/OTLScript#3]
My devices is 64bits, miui13

**Comment by kruvcraft21** [comment]
Provide more information. Personally, this feature works great for me.
![Screenshot_20230125-113358_Otherworld Legends.png](https://user-images.githubusercontent.com/33977897/214496758-26de4e3a-3b1a-4bec-9aca-e2dd43a22647.png)

![Screenshot_20230125-113401_Otherworld Legends.png](https://user-images.githubusercontent.com/33977897/214496788-6c7433f9-9071-48ea-8ae5-b2797b11c17a.png)

I also want to draw your attention to the fact that this function sometimes requires re-applying. 

And one more thing, this function cannot break all items, I wrote about this:
![Screenshot_20230125-113514_GitHub.png](https://user-images.githubusercontent.com/33977897/214497014-509ba37f-7e85-4b1d-a0a2-485cb1a64704.png)

**Comment by WuzenLiz** [comment]
Hey guy this function aren't work at newest version anymore
